language: node_js

node_js:
  - "4.0"

cache:
  directories:
  - $HOME/calibre-bin

sudo: false

env:
  global:
  - secure: Q2TEmWswcO6kQSwWfaI4bJxquU72r91V+qW69KckFXKAXrfK+yMKFZBYSZ1qNCtAkF7z4uUuJL3n+jxN7TI5AgDH3yya7LLfLqwT0OualJ+7WcROvLCudrfZ0WzjgDxVPtNAatn/p9XlXogHK0Br3NQMUB/YcHCmKGeVnnnqi9fLpu5OIMzPOcI25sdV3IwfmQ44kMxR9qnMaFfM8HPsVTjRUdurRm9M+8yEXnL3VsRLK7i3rXVm+j6kbec1YbANMtWeqUKbWI0Hqi63HdfyfqI0pBDUlaggFKnZvUUKNQ2dJDfv7xp73ozurFZOf1wt+/2jycIf9pAGVsieBhCpV+xsYvlKfanszH+5d63ra8Q25ljMVmSSGpLBnjD9rK0oijlXJuFI+HcVE0li3PfQlpeEna7VdlLpkpIJ0Mkdp7MueyRkicK5HiUweH/Mi8yOhfokKbZXyKdXnJtiyeS20Uk62ZfAw3WG4+us4oe63xQfy+eN2Hs73p8J35yVieAsw6CqHjmr/o72sWXGIpOM6FSHB7TVrX0tULAxxg+8tmB751Q/+6cDBde4eicT5eAJdlSwbQFLdfpuDT/6SQMRMtvRiv6VAWpQQ/LHag6oqf1m40WnuHfCs1wZ5pZ924o7GWo/7rNJfjC4/5KFWFySDPDtofQDihRAxxEVI4wBpnM=

before_script:
  - export PATH=$PATH:$HOME/calibre-bin/calibre
  - >
    which calibre ||
    wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py |
    python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('~/calibre-bin', True)"

script:
  - npm test

after_success:
  - ./ci/update-gh-pages.sh > /dev/null 2>&1

notifications:
  email:
    on_success: never
    on_failure: never
